### ISSUE TITLE
VOXELWORLD: Add island based world generation

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/vengi#10]
Island based world generation based on this blog post https://jobtalle.com/layered_voxel_rendering.html should be implemented. ~~In a way that only 2d heightmaps are combined (even for cliffs). These heightmaps can then be sent to the client to fix the float-based-noise differences.~~

**Comment by mgerhardy** [comment]
https://github.com/ganochenkodg/svelte-terrain

**Comment by mgerhardy** [comment]
https://www.redblobgames.com/x/1938-square-tiling-of-sphere/
https://www.redblobgames.com/x/1932-sphere-healpix/
https://www.redblobgames.com/x/1939-planetary-dungeon/
https://old.reddit.com/r/proceduralgeneration/comments/kaen7h/new_video_on_procedural_island_noise_generation/gfjmgen/

**Comment by trsh** [comment]
Noice =)))

**Comment by mgerhardy** [comment]
Now part of vengi-archive - so closing this one here.
