### ISSUE TITLE
UI: Risk of data concurrency at WindowStack class

### ISSUE THREAD

**Issue by Lecrapouille** [mgerhardy/vengi#105]
I do not know about this project, just looking at the code.

In WindowStack.cpp is there no risk of data concurrency between the update() method iterating over elements and calling push()/pop during() the update iteration ?

**Comment by mgerhardy** [comment]
You are right - there is a potential problem - pop and push should be delayed and only executed in the update() method.

**Comment by mgerhardy** [comment]
this is now in vengi-archived and removed from this repository.
