### ISSUE TITLE
VOXCONVERT: conversion roundtrip does not result in a bit-for-bit identical file

### ISSUE THREAD

**Issue by fgaz** [mgerhardy/vengi#113]
Conversion roundtrip does not result in an identical file:

```
vengi-voxconvert --input file1.format1 --output file2.format2
vengi-voxconvert --input file2.format2 --output file3.format1
diff file1.format1 file3.format1
```

The `diff` command reports a difference, at least with qb and vox formats.

By a quick inspection with a binary diff tool, it looks like some parts of the model (eg. leg and arm of chr_knight.qb) are getting shuffled around.

In the editor, the model appears unchanged.

Version 0.0.14 did a clean roundtrip with an extra conversion (qb -> vox -> qb -> vox). In version 0.0.17, the file changes after each iteration.

Relevant disabled test:

https://github.com/mgerhardy/vengi/blob/f05e4830936242520010aebd8da6218f153ca6c8/src/tools/voxconvert/tests/tests.sh.in#L19

**Comment by mgerhardy** [comment]
c5f3487d1a74e7684ef3de857b7e2c03cf183bc6 fixes the issue and
92ac770e1c397e50da3bc1fd3ee86ade664667dd activated the test again.

**Comment by mgerhardy** [comment]
https://github.com/jpaver/opengametools/commit/1eb03035e95ae9405a21d214dac747921d965ec4 this is the upstream fix for the issue
