### ISSUE TITLE
VOXCONVERT: Resizing Volume Issue

### ISSUE THREAD

**Issue by LordKromdar** [mgerhardy/vengi#116]
Original file is 90x90x132
![image](https://user-images.githubusercontent.com/38475000/155009739-de3bcb89-2ffc-4c7a-8a29-48daf27f40f3.png)

Merged file is changed to 126x126x126

![image](https://user-images.githubusercontent.com/38475000/155009810-e4f1d177-b894-4d21-9fb1-f2065781ca21.png)

Using command:

vengi-voxconvert -set palette palette-nippon.png --force --merge --flip x --input layered.vox --output flattened.vox

**Comment by LordKromdar** [comment]
[ahsoka3_blank.zip](https://github.com/mgerhardy/vengi/files/8111481/ahsoka3_blank.zip)

File in question attached.

**Comment by mgerhardy** [comment]
The second layer in the attached vox file has a bigger volume size as the first one - when merging the layers voxconvert will expand the new volumes in a way that both of the other volumes fit into it. I'll validate the sizes just to be sure.

**Comment by LordKromdar** [comment]
The same function but outputting VXM yields the correct results. Output to vox trims some voxel volume from the top

**Comment by mgerhardy** [comment]
Maybe related to `Format::splitVolumes`

**Comment by mgerhardy** [comment]
There was a problem in merging the volumes that was addressed with commit 3367951a7097bc0d41f920029ee10ce7422b00ad. maybe that already fixes the issue.

**Comment by mgerhardy** [comment]
![Bildschirmfoto von 2022-03-10 07-54-17](https://user-images.githubusercontent.com/577713/157605898-a9663bfe-6bdb-4ac4-99cd-a2e40f511a57.png)

As far as I can say the mentioned commit fixed the issue. If not, please re-open
