### ISSUE TITLE
VOXCONVERT: Converted VXMs Rendering Certain Colored Voxels Incorrectly

### ISSUE THREAD

**Issue by LordKromdar** [mgerhardy/vengi#117]
Certain colors are displaying strangely in converted VXMs. Original vox, palette, and converted VXM attached in zip.

![image](https://user-images.githubusercontent.com/38475000/155190946-fcded4b9-656a-4ed6-b606-bf37c9af1b8f.png)
[ahsoka1.zip](https://github.com/mgerhardy/vengi/files/8119048/ahsoka1.zip)

**Comment by LordKromdar** [comment]
Problem is solved by using a different palette, but using the original palette in most files results in these voxel bars

**Comment by mgerhardy** [comment]
Can you please post the exact commandline you used to convert the model? Did you try `--src-palette`?

**Comment by LordKromdar** [comment]
vengi-voxconvert.exe --src-palette --export-palette --force --merge --flip x --input original.vox --output converted.vxm

**Comment by mgerhardy** [comment]
Most related to the fact that VXM models are using the last palette entry for empty voxels - while we are using the first one (more or less - we are using the voxel type Air with palette index 0)

**Comment by mgerhardy** [comment]
a551ed5a4c53560551de8e183f2764d36f76c86d

**Comment by mgerhardy** [comment]
This is hopefully fixed now. If not, please re-open
