### ISSUE TITLE
Voxedit: I can not "create/place" any voxel.

### ISSUE THREAD

**Issue by mdtrooper** [mgerhardy/vengi#140]
I am trying to create/place a voxel in the voxedit with the left button of mouse and control/shift and arrows keys and it not appear. 

```
$ lsb_release --all
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una

$ uname -a
Linux pc-panacea 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ dpkg -l | grep vengi
ii  vengi-shared                                                0.0.19.0-1                                                   amd64        Shared stuff like mimetypes
ii  vengi-voxconvert                                            0.0.19.0-1                                                   amd64        Convert, export or modify voxel volumes
ii  vengi-voxedit                                               0.0.19.0-1                                                   amd64        Voxel editor
```

**Comment by mgerhardy** [comment]
You are maybe in scene mode. I‘ve improved the default settings to be edit mode for a single model or a new scene now. I see that this is very confusing.

**Comment by mdtrooper** [comment]
Yes, thanks I found it:

![imagen](https://user-images.githubusercontent.com/1285451/161351442-a8a7dab9-75c7-40d5-acc1-90718c2e96fd.png)


And I can "made" something to test:

![imagen](https://user-images.githubusercontent.com/1285451/161351467-dd2073f4-59fc-49ef-9285-c8413cc6acd4.png)

**Comment by mdtrooper** [comment]
Maybe it is good idea put in somepacle (such as the title bar or at the right in toolbar....) a "status/mode indicator" as "scene mode on/off" or something.

And too maybe it is good idea to start the editor in "edit mode".

**Comment by mgerhardy** [comment]
Thanks a lot for the suggestions. I will improve this.

**Comment by mgerhardy** [comment]
0575990fe0116790597502b9aca61fc1931d7bc3 and 7a90f715142c511a347b5e4b7ccb7d7d8de2b340 improved the situation on this.

**Comment by mdtrooper** [comment]
I just check it (with a compilation from the last commit). It is runs fine, it starts in "edit mode".
