### ISSUE TITLE
VOXEDIT 0.0.19: Show a lot of bugs when delete the first layer

### ISSUE THREAD

**Issue by mdtrooper** [mgerhardy/vengi#141]
The steps are:
 - Start voxedit
 - Create 2º layer
 - Delete 1º default layer
 - Go to the scene graph
 - Open the tree with the right arrow icon.

![imagen](https://user-images.githubusercontent.com/1285451/161351870-4d82e42d-b7bc-49ae-b19c-37c0253d4181.png)

**Comment by mgerhardy** [comment]
thanks for the report. fixed in 4ed388d56edfb0d701eae77c7ae934a5e1888e0e

**Comment by mdtrooper** [comment]
Ok, another bug fixed. I tried in the last commit and now its runs fine.
