### ISSUE TITLE
VOXEDIT: The GUI goes crazy when press the key arrows and it is in edit mode

### ISSUE THREAD

**Issue by mdtrooper** [mgerhardy/vengi#142]
Version 0.0.19

When I was trying to made something in #140 . I read on the documentation that I can use the arrow keys. And voxedit went crazy but I had not time (I was in my job time, I can some minutes of spare time when I am working but not 1 hour or more ;) ) to record in a screencast the bug.

But some hours ago (now it is the late night in Spain) I can do a screencast with OBS and screenkey.

With the first press left key, the GUI goes crazy and move quickly and random the focus between almost of widgets on the window....they are flashing and set the white border as Christmas tree and it is looping the bug forever (well I was more or less 10 minutes but the screencast is the 2 minutes ).

https://user-images.githubusercontent.com/1285451/161353899-436c11e1-b261-4e45-b1eb-7c1bce1d4e33.mp4

Ok, it is a bug, but your project is awesome, thanks :beers: .

**Comment by mgerhardy** [comment]
Thanks a lot of this detailed bug report. Will investigate

**Comment by mgerhardy** [comment]
I can not reproduce this - is this on windows linux or osx?

**Comment by mdtrooper** [comment]
It is a Linux (I hope it...ohh just kidding ;) ).

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 20.3
Release:	20.3
Codename:	una

$ uname -a
Linux pc-panacea 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ dpkg -l | grep vox
ii  vengi-voxconvert                                            0.0.19.0-1                                                   amd64        Convert, export or modify voxel volumes
ii  vengi-voxedit                                               0.0.19.0-1                                                   amd64        Voxel editor
```

**Comment by mgerhardy** [comment]
Is this wayland already?

**Comment by mdtrooper** [comment]
No, It is xorg (I did'nt remember but I found this command):

```
$ loginctl show-session c2 -p Type  
Type=x11
```

**Comment by mgerhardy** [comment]
I was able to reproduce it now. the arrow keys are used to navigate the ui and are bound to actions. it was possible to press a key and don't inform the ui when its released.

**Comment by mgerhardy** [comment]
should be fixed now. if not, please reopen
