### ISSUE TITLE
BUILD: Fails to compile on ubuntu 22.04 - lua 5.4 issue

### ISSUE THREAD

**Issue by guillaumechereau** [mgerhardy/vengi#172]
I just tried to compile the code on my machine, but it fails with this error:

/usr/bin/luac: ...rc/modules/voxelgenerator/lua/scripts/modules/volume.lua:76: unexpected symbol near '<'

I have lua 5.2.4 installed on the machine (default for ubuntu I assume).

**Comment by RobertZenz** [comment]
```lua
76: local offset <const> = {
```

`<const>` is a Lua 5.4 keyword. The [Dependency-Section of the documentation](https://mgerhardy.github.io/vengi/Dependencies/) also does list Lua 5.4.

**Comment by mgerhardy** [comment]
I suppose the error then is in the build scripts - as it should ignore your system-wide lua installation. The cmake scripts should check for lua >= 5.4

**Comment by mgerhardy** [comment]
As a workaround you can just uninstall the `liblua5.2-0-dev` package

**Comment by mgerhardy** [comment]
Can you please tell me where you lua headers are installed? they should be in `/usr/include/lua5.2/`, no?

**Comment by guillaumechereau** [comment]
Yes the headers are in /usr/include/lua5.2/.  Removing the const from the script works so I'll do it like that for now.

**Comment by mgerhardy** [comment]
Should be fixed now. If not, please re-open. Thanks a lot for the report.
