### ISSUE TITLE
VOXEDIT: Cannot start on Windows

### ISSUE THREAD

**Issue by EsraBerfinErtan** [mgerhardy/vengi#183]
When we click and run the exe many times it immediately exits. It can't open. After too many clicks it may open and run succesfully. After it run succesfully, sometimes it crashes again after I create a cube or sth. I couldn't solve this problem. I built it with Visual Studio Community 2019 Release - amd64

It gives stacktrace like this when I start it from command line:
![image](https://user-images.githubusercontent.com/69576164/194348780-54e9253b-6548-417d-babe-095fd6136453.png)

**Comment by mgerhardy** [comment]
Thanks for the report.

* First question is whether the most recent nightly build version from the discord night build channel or the github action download works on your system?
* Second would be a few more details about your system - like os and graphic card
* Last but not least would be whether you compiled this in release or debug mode
