### ISSUE TITLE
VOXEDIT: Macbook: Some content not shown in the window.

### ISSUE THREAD

**Issue by midstreeeam** [mgerhardy/vengi#190]
I am currently using M1 Macbook. After I download and open the release version, I found the resolution of the window is weird. Buttons and side bars seem too big.
![image](https://user-images.githubusercontent.com/105056239/199389687-ff19c7b1-946f-4af6-8189-a6689dc168fb.png)
I don't know if there is any settings to adjust it.

**Comment by mgerhardy** [comment]
this might be an issue with ui_fontsize setting. Open the console with `ctrl+tab` and type `ui_fontsize 12` and hit enter

this setting is also accessible from the edit->options menu:
![Bildschirmfoto vom 2022-11-02 20-29-20](https://user-images.githubusercontent.com/577713/199584903-9e2e82a7-5809-4f7a-bb81-ad7451380c42.png)

**Comment by midstreeeam** [comment]
Thanks for your reply! I tried to change the ui font size, but no matter how I adjust it, some button (mainly the bottom bar) still not shown. Also, as I lower the ui font size, the ui resolution seems to become very low that all words are blur. Here is a screen shot.
I don't know if it is caused by my computer settings.
![image](https://user-images.githubusercontent.com/105056239/199893354-28091684-7f66-417c-97b2-8b797bdfbc91.png)

**Comment by mgerhardy** [comment]
this looks like a high dpi issue (retina display)

**Comment by mgerhardy** [comment]
You you please attach your log file?

`/Users/bob/Library/Application Support/vengi/voxedit/log.txt`

**Comment by midstreeeam** [comment]
I just download latest dmg file and run it, so I think I don't have `vengi` folder under `Library/Application Support`. Is that the problem? Or do I need to download the source code to compile myself?

**Comment by mgerhardy** [comment]
There are a few changes incoming to improve the situation for high dpi

**Comment by mgerhardy** [comment]
these three commits should improve the high dpi support. feedback would be nice - I can't validate this.
5ffdcd3fb15ef61edf82e34f53fdc9f08c55a4c9
fcdb1c8893ae71f73f3ba0a0a682538daf28d0f5
aa259857f74489e8b5cb507f6018782df5f993c3

**Comment by mgerhardy** [comment]
closing this for now - if there are still problems left - please reopen.

**Comment by yurii-karadzhov** [comment]
Nothing changes. This is how master build look like on latest MacOS
<img width="1680" alt="Screenshot 2022-12-30 at 17 59 48" src="https://user-images.githubusercontent.com/56255894/210091130-82b0f2fe-18fb-4f83-98c8-b88e93ea88ed.png">

**Comment by yurii-karadzhov** [comment]
log.txt content is not very helpful
```log
[WARN] (0) could not get a valid key code for left alt (skip binding for +camera_pan)
[WARN] (0) could not get a valid key code for right alt (skip binding for +camera_pan)

```

**Comment by mgerhardy** [comment]
@yurii-karadzhov Sorry, but that can't be the master build from 30.12.2022 - also what makes you think that it isn't working as expected? Imo it looks quite useable - (see the first screenshot of the issue). Was your screenshot made in highdpi mode? If you find something not working as expected, please open a ticket or add a detailed description about the issue.
