### ISSUE TITLE
VOXEDIT: Modifiers shouldn't be ticked, they should be directly choosable, also should be smaller.

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/vengi#208]
![image](https://user-images.githubusercontent.com/577713/208710023-767c615b-a862-4069-b21d-10558d919238.png)![image](https://user-images.githubusercontent.com/577713/208710163-593e94b9-30bb-4d4c-9160-cf1db063a8e5.png)![image](https://user-images.githubusercontent.com/577713/208710104-fbf34466-558b-42f3-b096-1e55b52a662e.png)

**Comment by mgerhardy** [comment]
Possible icons include:
* https://forkaweso.me/Fork-Awesome/icons/
* https://fontawesome.com/search?m=free&o=r

A list of icons to use would be nice

**Comment by karmahub95** [comment]
https://fontawesome.com/icons/cube?s=solid&f=classic This one is for "Place".

https://fontawesome.com/icons/diagram-next?s=solid&f=classic This one is for "Override".
