### ISSUE TITLE
VOXEDIT: Tools/ rotate on axis/ Gizmo should be added. Rotate on axis changes objects shape

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/vengi#210]
![image](https://user-images.githubusercontent.com/577713/208710270-23b7a12f-cb91-4af5-9720-3aa075fbf7d7.png)

**Comment by EsraBerfinErtan** [comment]
![image](https://user-images.githubusercontent.com/69576164/214076737-79034391-b2c5-4f2e-9191-bcb012366c72.png)

![image](https://user-images.githubusercontent.com/69576164/214076775-843e3500-a61f-4ab2-98cc-954d4d74ab2b.png)

![image](https://user-images.githubusercontent.com/69576164/214076829-29a033e0-9054-4970-bb06-7343022aa342.png)


When we use the rotate on axis buttons, the rectangular object becomes striped and perforated as in the image. As you can see at first the object is just a rectangle with no details.

**Comment by mgerhardy** [comment]
![rotate_assert](https://user-images.githubusercontent.com/577713/214127561-295567af-befb-4566-a638-72952e2dbd0d.png)

**Comment by mgerhardy** [comment]
I have opened the scene mode then in scene mode i moved the object, then when i entered the editmode and used the rotate on axis function this happens

**Comment by mgerhardy** [comment]
I think works as designed now. The rotate on axis features are no longer visible when in scene mode now.

in scene mode you can rotate around the pivot - in model node, you rotate the whole volume. If this isn't what was meant here, please let me know.
