### ISSUE TITLE
VOXEDIT: Color radial should be placed in the palette window.

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/vengi#212]
![image](https://user-images.githubusercontent.com/577713/208710336-255f59f9-22a0-4439-b3d7-9a897c463b71.png)

**Comment by karmahub95** [comment]
![main_colorwheel](https://user-images.githubusercontent.com/96667893/209667536-ec03e699-c6da-4f0d-8fd6-d2fae2271c46.jpg)

As in the image above, the colour wheel should be static within the palette window tab.
