### ISSUE TITLE
VOXEDIT: The folder system should be simplified.

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/vengi#215]
![image](https://user-images.githubusercontent.com/577713/208710558-27877c64-2ec4-4697-a67a-12038cc1f32d.png)

**Comment by mgerhardy** [comment]
I need more information on what should be changed here. How it can be improved. It's kind of modeled after the osx finder https://osxdaily.com/wp-content/uploads/2010/02/mac-os-x-finder-column-view.JPG

**Comment by EsraBerfinErtan** [comment]
![save_as_image](https://user-images.githubusercontent.com/69576164/209562434-95beccc2-7e7f-4a55-9916-40c70fb1be21.png)

**Comment by mgerhardy** [comment]
What do you mean with to complex? What should be in there exactly - any kind of grouping?

**Comment by EsraBerfinErtan** [comment]
We want a window with this simplicity as seen in this photo. In this regard, we think that the save window of Windows has the design closest to what we want.

![image](https://user-images.githubusercontent.com/69576164/210787200-614e732e-bf15-4d7b-b4d9-eb5401d12be8.png)

**Comment by mgerhardy** [comment]
https://github.com/dfranx/ImFileDialog might be an option

**Comment by mgerhardy** [comment]
![Bildschirmfoto vom 2023-02-05 19-54-12](https://user-images.githubusercontent.com/577713/216839046-314d8b12-2e21-4382-96e6-dcf7b52bbff6.png)
![Bildschirmfoto vom 2023-02-05 19-54-02](https://user-images.githubusercontent.com/577713/216839048-48fb21d4-d6b0-42b3-9016-688cd54a1108.png)

here is how it looks atm - not yet done though.
