### ISSUE TITLE
VOXEDIT: Button preferences should be given to the user instead of positions/region

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/vengi#217]
These buttons

![image](https://user-images.githubusercontent.com/577713/208713530-a9acbb23-954a-4c25-81e6-7712d87c0811.png)

It should be 10x10, 30x30, 60x60, 120x120, 240x240.

**Comment by EsraBerfinErtan** [comment]
Normally, in the "Size" section, we wanted it in the form of buttons, as you can see. The area part is like 10x10 30x30 60x60.... Please make this height 70 for all fields. The size we call 10x10 mentioned here is actually the cube size in Voxedit. 1 cube = 1 unit. 10 cubes = 10 units. Like 10x10 = 10 cubes x 10 cubes. Like 10x10x70 or 60x60x70. 

"default configurable via cvar csv?" Yes its okay.
