### ISSUE TITLE
VOXELFORMAT: slow .qb input

### ISSUE THREAD

**Issue by p0nce** [mgerhardy/vengi#261]
Both voxedit and voxconvert struggle to have this file as input, it takes minutes and I never finished such an input, stuck at 10% CPU usage.
But that .qb file loads quite fast in goxel.

The file = https://u.pcloud.link/publink/show?code=XZOrCxVZn0k50z7Grcp8HeRETQiCL7Ca80X0

**Comment by mgerhardy** [comment]
Thanks a lot for the report - I will investigate. Which software was used to create the qb file - is that known?

**Comment by mgerhardy** [comment]
The slowdown comes from the palette creation - looks like the qb files uses a lot of different but very similar colors. vengi is built around a 256 color palette and finding the best match for a given color is taking a lot of time for this model. Once i skip the palette creating, the loading is quite fast - but the result is not nice
![Bildschirmfoto vom 2023-03-25 17-09-12](https://user-images.githubusercontent.com/577713/227728759-a98200fd-14cc-41bd-a455-ded63822bf19.png)

**Comment by mgerhardy** [comment]
This is fixed now by using the cvars `voxformat_rgbflattenfactor` and `core_colorreduction`. See https://mgerhardy.github.io/vengi/Configuration/ for more details.

`voxformat_rgbflattenfactor` set to e.g. `2` produces this result in a few seconds
![Bildschirmfoto vom 2023-03-25 17-38-35](https://user-images.githubusercontent.com/577713/227730197-5108c888-f781-4937-9cc3-118e11f08a68.png)

**Comment by p0nce** [comment]
> Which software was used to create the qb file - is that known?

I generated it. Thanks!

**Comment by mgerhardy** [comment]
I'll close this as fixed then - if you still encounter problems, please re-open with the details. Thanks again for the report.

**Comment by p0nce** [comment]
Thanks!
