### ISSUE TITLE
VOXEDIT: Merge not working right

### ISSUE THREAD

**Issue by DryByte** [mgerhardy/vengi#272]
When trying to merge 2 models from same group it merges all nodes from the file.
In the screenshot below im trying to merge two custom_tree1, but it merges all models into root. Also tried using the "merge locked" and "merge visible", both not works how it was supposed to work.

![](https://cdn.discordapp.com/attachments/929064020626014258/1097250918715637841/Screenshot_2023-04-16-05-03-14_1360x768.png)

**Comment by mgerhardy** [comment]
Should be fixed now. - if not please re-open or create a new ticket with the details
