### ISSUE TITLE
Generates invalid gltf

### ISSUE THREAD

**Issue by stefnotch** [mgerhardy/vengi#277]
When running `vengi-voxconvert.exe --input "entrance.vox" --output entrance.gltf`, then I do get a gltf file. However, that file is invalid, and as such, Blender 3.5 refuses to open it.

The validity of the gltf file can be tested using https://github.khronos.org/glTF-Validator/

Apparently it's not happy about the cameras with a znear and zfar of 0.

Here's the test file. [Please rename it to entrance.vox](https://github.com/mgerhardy/vengi/files/11289125/entrance.txt)

On that note, I also noticed that the transformations might be off. I'll gladly open a new issue for that.

Version: 0.0.24

**Comment by mgerhardy** [comment]
should be fixed - thanks a lot for the report.
