### ISSUE TITLE
VOXEDIT: Fonts look blurry

### ISSUE THREAD

**Issue by jerobarraco** [mgerhardy/vengi#293]

**Comment by mgerhardy** [comment]
I would need more details here. What is your fontsize? What’s your dpi and so on. Maybe a screenshot and the cfg file from your home dir

**Comment by jerobarraco** [comment]
Font size don't matter. some sizes look better other worse. but all do look bad. lines are sharp. but no font is good.
![image](https://github.com/mgerhardy/vengi/assets/3729895/847b972c-5246-4277-904c-33ef67191b4f)

im using 4k. on kde. at 200% ui scale. 150% has the same effect too. fonts dpi are set at 192 system wide. (can't change this without breaking all other apps)

where is the cfg file?

**Comment by jerobarraco** [comment]
this screenshot you've posted also looks blurry to me. 
https://discord.com/channels/622817134682177555/952166615393386506/1085091459126009856

could it be anti-aliasing?

**Comment by mgerhardy** [comment]
cfg file is in: `~/.local/share/vengi/voxedit/voxedit.vars`

maybe try to set `cl_highdpi` to `true`

**Comment by mgerhardy** [comment]
![Bildschirmfoto vom 2023-05-17 20-26-42](https://github.com/mgerhardy/vengi/assets/577713/e79a8cdb-b7ed-4626-a3fd-1f8403d72937)

should be fixed now.

**Comment by jerobarraco** [comment]
can confirm this is working on this build https://github.com/mgerhardy/vengi/actions/runs/5006686301
