### ISSUE TITLE
VOXEDIT: Can't get vertex colors working on UE5

### ISSUE THREAD

**Issue by jerobarraco** [mgerhardy/vengi#294]
i've exported some gltf assets into ue5 and i can't get the colors to show.

In the unreal mesh viewer the vertex colors shows as white. and using the same material i used for other gltfs it also shows as white.

apparently the colors are being exported.

is there any hindsight i can get from the format and values of these colors?

**Comment by mgerhardy** [comment]
does it work when you export with uv map and textures?

**Comment by mgerhardy** [comment]
also, do you need animations or something other more advanced, otherwise you can also try to import obj. just to see if vertex colors are working at all as they should in ue5. I don't have the ue5 editor running atm - I will compile it asap and try to be of better help here.

**Comment by jerobarraco** [comment]
I don't need animations for now so i will try objs.
I will try better tomorrow.

> does it work when you export with uv map and textures?

i haven't tried. but i also want to stay away from textures so it's not a solution for me. but i will try it anyway to narrow down the issue.

**Comment by mgerhardy** [comment]
It's 21GB - and I don't have that much free space on my hard drive to install this atm.

**Comment by mgerhardy** [comment]
https://www.reddit.com/r/unrealengine/comments/eupiv5/vertex_colors_not_importing_from_blender/

> Worth noting; Unreal import defaults to Ignoring vertex colors when reimporting models. It’s important to select ‘Replace’ if you’re reimporting, to prevent your models from losing data in the process.
> It’s in General Import Settings somewhere

**Comment by jerobarraco** [comment]
btw, if you want to download a smaller version in the epic installer when installer if you click Options when selecting the folder you can remove a bunch of unnecessary stuff. (all of it).

**Comment by jerobarraco** [comment]
i can import obj assets into ue but the colors still doesn't work.

**Comment by mgerhardy** [comment]
vertex colors for obj is an "extension" (or abuse of the standard) - looks like unreal doesn't support it.

you could still export the colors as png file - it's just about 256 rgba colors - you can even put them into your unreal code and just use the uv data to colorize the mesh.

**Comment by jerobarraco** [comment]
Thanks,  i know, but what i'm trying to avoid is sampling the texture, also that would mean i have to use uvs. and possibly its going to be different uvs for different models. i work with several different files.

i tried several things but still this doesn't work. 
vertex colors on ue do work. when i use goxel for example they work correctly.

**Comment by mgerhardy** [comment]
If it is float color related - i might have a compatibility fix in latest `master`. 

The cvar `voxformat_colorasfloat` can be set to false to use bytes for the color.

`vengi-voxconvert --input input.vox --output output.gltf -set voxformat_colorasfloat false`

for voxedit the option is in the file dialog

![Bildschirmfoto vom 2023-07-31 13-15-38](https://github.com/mgerhardy/vengi/assets/577713/5ae7721e-14e5-473b-83b0-3ac8771af6f2)

**Comment by mgerhardy** [comment]
Please let me know whether the latest changes regarding the color type fixes the issue for unreal being able to import the colors properly.

**Comment by mgerhardy** [comment]
Closing the ticket for now - I have no way to validate the fix. If it's still an issue, please reopen the ticket.

**Comment by jerobarraco** [comment]
thanks, i could not confirm this working yet since i cant import the mesh. https://github.com/mgerhardy/vengi/issues/295#issuecomment-1672441458
i will open a new ticket for that when i have time.
