### ISSUE TITLE
VOXELFORMAT: UE5 crashes on importing glft exported from voxedit

### ISSUE THREAD

**Issue by jerobarraco** [mgerhardy/vengi#295]
Some models do this. created from 0.

This is with the latest release on github as a deb package.

[test.gltf.txt](https://github.com/mgerhardy/vengi/files/11528735/test.gltf.txt)
i know this sounds like a bug in ue. but it doesnt happen with other tools and makes vengi unusable for ue.

stack:

```
LoginId: redacted
EpicAccountId:

Caught signal 11 Segmentation fault

libUnrealEditor-GLTFCore.so!GLTF::FValidAccessor::GetVec4Array(UE::Math::TVector4<float>*) const [/home/nande/work/UE5.2/Engine/Source/./../Plugins/Editor/GLTFImporter/Source/GLTFCore/Private/GLTF/GLTFAccessor.cpp:546]
libUnrealEditor-GLTFCore.so!GLTF::FMeshFactoryImpl::ImportPrimitive(GLTF::FPrimitive const&, int, int, bool, bool, TMeshAttributesRef<FVertexInstanceID, UE::Math::TVector<float> > const&, TMeshAttributesRef<FVertexInstanceID, UE::Math::TVector<float> > const&, TMeshAttributesRef<FVertexInstanceID, float> const&, TMeshAttributesRef<FVertexInstanceID, UE::Math::TVector2<float> > const&, TMeshAttributesRef<FVertexInstanceID, UE::Math::TVector4<float> > const&, TMeshAttributesRef<FEdgeID, bool> const&, FMeshDescription*, bool) [/home/nande/work/UE5.2/Engine/Source/./../Plugins/Editor/GLTFImporter/Source/GLTFCore/Private/GLTFMeshFactory.cpp:331]
libUnrealEditor-GLTFCore.so!GLTF::FMeshFactoryImpl::FillMeshDescription(GLTF::FMesh const&, FMeshDescription*) [/home/nande/work/UE5.2/Engine/Source/./../Plugins/Editor/GLTFImporter/Source/GLTFCore/Private/GLTFMeshFactory.cpp:229]
libUnrealEditor-InterchangeImport.so!UE::Interchange::Gltf::Private::GetStaticMeshPayloadDataForPayLoadKey(GLTF::FAsset const&, FString const&, UE::Interchange::FStaticMeshPayloadData&) [/home/nande/work/UE5.2/Engine/Source/./../Plugins/Interchange/Runtime/Source/Import/Private/Gltf/InterchangeGltfMesh.cpp:283]
libUnrealEditor-InterchangeImport.so!UE::Core::Private::Function::TFunctionRefCaller<UInterchangeGltfTranslator::GetStaticMeshPayloadData(FString const&) const::$_30, TOptional<UE::Interchange::FStaticMeshPayloadData> ()>::Call(void*) [/home/nande/work/UE5.2/Engine/Source/Runtime/Core/Public/Templates/Function.h:465]
libUnrealEditor-InterchangeImport.so!TAsyncGraphTask<TOptional<UE::Interchange::FStaticMeshPayloadData> >::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&) [/home/nande/work/UE5.2/Engine/Source/Runtime/Core/Public/Async/Async.h:127]
libUnrealEditor-InterchangeImport.so!TGraphTask<TAsyncGraphTask<TOptional<UE::Interchange::FStaticMeshPayloadData> > >::ExecuteTask(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type, bool) [/home/nande/work/UE5.2/Engine/Source/Runtime/Core/Public/Async/TaskGraphInterfaces.h:1310]
libUnrealEditor-Core.so!void LowLevelTasks::FTask::Init<FTaskGraphCompatibilityImplementation::QueueTask(FBaseGraphTask*, bool, ENamedThreads::Type, ENamedThreads::Type)::'lambda'()>(char16_t const*, LowLevelTasks::ETaskPriority, FTaskGraphCompatibilityImplementation::QueueTask(FBaseGraphTask*, bool, ENamedThreads::Type, ENamedThreads::Type)::'lambda'()&&, LowLevelTasks::ETaskFlags)::'lambda'(bool)::operator()(bool) const [/home/nande/work/UE5.2/Engine/Source/Runtime/Core/Public/Async/Fundamental/Task.h:499]
libUnrealEditor-Core.so!LowLevelTasks::TTaskDelegate<LowLevelTasks::FTask* (bool), 48u>::TTaskDelegateImpl<void LowLevelTasks::FTask::Init<FTaskGraphCompatibilityImplementation::QueueTask(FBaseGraphTask*, bool, ENamedThreads::Type, ENamedThreads::Type)::'lambda'()>(char16_t const*, LowLevelTasks::ETaskPriority, FTaskGraphCompatibilityImplementation::QueueTask(FBaseGraphTask*, bool, ENamedThreads::Type, ENamedThreads::Type)::'lambda'()&&, LowLevelTasks::ETaskFlags)::'lambda'(bool), false>::CallAndMove(LowLevelTasks::TTaskDelegate<LowLevelTasks::FTask* (bool), 48u>&, void*, unsigned int, bool) [/home/nande/work/UE5.2/Engine/Source/Runtime/Core/Public/Async/Fundamental/TaskDelegate.h:171]
libUnrealEditor-Core.so!LowLevelTasks::FTask::ExecuteTask() [/home/nande/work/UE5.2/Engine/Source/Runtime/Core/Public/Async/Fundamental/Task.h:627]
libUnrealEditor-Core.so!LowLevelTasks::FScheduler::ExecuteTask(LowLevelTasks::FTask*&) [/home/nande/work/UE5.2/Engine/Source/./Runtime/Core/Private/Async/Fundamental/Scheduler.cpp:150]
libUnrealEditor-Core.so!bool LowLevelTasks::FScheduler::TryExecuteTaskFrom<LowLevelTasks::TLocalQueueRegistry<1024u>::TLocalQueue, &(LowLevelTasks::TLocalQueueRegistry<1024u>::TLocalQueue::DequeueGlobal(bool, bool)), false>(LowLevelTasks::TLocalQueueRegistry<1024u>::TLocalQueue*, LowLevelTasks::TLocalQueueRegistry<1024u>::FOutOfWork&, bool, bool) [/home/nande/work/UE5.2/Engine/Source/./Runtime/Core/Private/Async/Fundamental/Scheduler.cpp:349]
libUnrealEditor-Core.so!LowLevelTasks::FScheduler::WorkerMain(LowLevelTasks::FSleepEvent*, LowLevelTasks::TLocalQueueRegistry<1024u>::TLocalQueue*, unsigned int, bool) [/home/nande/work/UE5.2/Engine/Source/./Runtime/Core/Private/Async/Fundamental/Scheduler.cpp:378]
libUnrealEditor-Core.so!FThreadImpl::Run() [/home/nande/work/UE5.2/Engine/Source/./Runtime/Core/Private/HAL/Thread.cpp:67]
libUnrealEditor-Core.so!FRunnableThreadPThread::Run() [/home/nande/work/UE5.2/Engine/Source/./Runtime/Core/Private/HAL/PThreadRunnableThread.cpp:25]
libUnrealEditor-Core.so!FRunnableThreadPThread::_ThreadProc(void*) [/home/nande/work/UE5.2/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.h:187]
libc.so.6!UnknownFunction(0x94b42)
libc.so.6!UnknownFunction(0x1269ff)
```

**Comment by jerobarraco** [comment]
btw i just had a hunch, given that it has a crash in getvec4 on a segfault. i wonder if vengi is exporting the values as RGB instead of RGBA (because A sounds redundant if you use materials, but if you use vertex colors they are not).
https://github.com/mgerhardy/vengi/issues/294

**Comment by mgerhardy** [comment]
It's exported as RGBA - I have no idea why this segfaults in Unreal, I've used several online viewers to show the model, imported it in blender, used the gltf validator - I don't see a problem on my side.

**Comment by jerobarraco** [comment]
Thanks a lot for that. its not obvious from your comment what would be a patch. 
if you have a suggestion lmk so that i can try changing it. i compile the engine from source.

**Comment by jerobarraco** [comment]
The thing that is weird to me is that other tools doesn't crash the engine. so _some_ difference should be there. (not saying this is a problem in vengi but it means it could clue me into how to fix it).

this is an object i made with goxel and it works.

[Cabinet00-frame.gltf.zip](https://github.com/mgerhardy/vengi/files/11537498/Cabinet00-frame.gltf.zip)

**Comment by jerobarraco** [comment]
i opened the files with pygltflib https://pypi.org/project/pygltflib/ and found these

voxedit:
```
>>> gltf.bufferViews
[BufferView(extensions={}, extras={}, buffer=0, byteOffset=0, byteLength=60912, byteStride=None, target=34963, name=None), BufferView(extensions={}, extras={}, buffer=0, byteOffset=60912, byteLength=284256, byteStride=28, target=34962, name=None)]
```

goxel:
```
>>> o.bufferViews
[BufferView(extensions={}, extras={}, buffer=1, byteOffset=0, byteLength=18312, byteStride=None, target=None, name=None), BufferView(extensions={}, extras={}, buffer=0, byteOffset=0, byteLength=195328, byteStride=32, target=None, name=None)]
```

the main difference i noted is that in voxedit the bytestride is 28, which means 7 bits per pixel? on 4 components (rgba) 3 components is 9.333333333333333 which is not reasonable.

on goxel is 32. which makes sense a normal 8bit per chanel 32 bit pixel.
that could totally exhaust the buffer. 

another diff is that voxedit seem sto use only 1 buffer and use a buffer offset. whereas goxel seems to use 2 buffers.

notes:
i have no idea what those buffers are, im just assuming.
i only tested 1 file from each.

is there a way you can verify the bitstride of each pixel?

**Comment by jerobarraco** [comment]
also i noted something. the componentType on gltf is set to 5126 on both buffers
which according to UE is a float of 32 bit (will crash as there's less data).
but i couldn't find anywhere a 28bit component type. 
nor i cant find the stride on the gltf file, i wonder how pygltflib gets it.

```    },
    {
      "bufferView": 1,
      "componentType": 5126,
      "count": 10152,
      "max": [
        27.0,
        18.0,
        32.0
      ],
      "min": [
        0.0,
        0.0,
        7.0
      ],
      "type": "VEC3"
    },
    {
      "bufferView": 1,
      "byteOffset": 12,
      "componentType": 5126,
      "count": 10152,
      "type": "VEC4"
    }
```
(Please disregard the fact that this is a link to 5.1 im using 5.2 but iirc it crashes on both)
https://github.com:EpicGames/UnrealEngine/blob/5.1/Engine/Plugins/Editor/GLTFImporter/Source/GLTFCore/Private/GLTF/ConversionUtilities.h#L207-L226

**Comment by mgerhardy** [comment]
>the main difference i noted is that in voxedit the bytestride is 28, which means 7 bits per pixel? on 4 components (rgba) 3 components is 9.333333333333333 which is not reasonable.

this is not 7 bits per pixel - but 28 bytes per entry. it's a packed buffer where the vertex data is using 28 bytes for each entry. It is possible that there must be padding - so a bytestride of 32 bytes. I have to check the gltf standard for this. But I still think that most likely unreal is doing something wrong here. It should segfault at all - no matter what the input it - and other tools are rendering the gltf files just fine.

**Comment by mgerhardy** [comment]
It looks like goxel isn't using packed buffers - it is using one buffer for each component of a vertex.

**Comment by jerobarraco** [comment]
>most likely unreal is doing something wrong here. It shouldn't segfault at all - no matter what the input is -

I can understand that, and that other tools can circumvent this, but that's what happens with ue5 currently.
how can i move forward?
is there a chance to export using 32 bytes per entry?

**Comment by jerobarraco** [comment]
i noticed that this doesn't happen if i have "export uvs" enabled.

**Comment by mgerhardy** [comment]
If it is float color related - i might have a compatibility fix in latest `master`. 

The cvar `voxformat_colorasfloat` can be set to false to use bytes for the color.

`vengi-voxconvert --input input.vox --output output.gltf -set voxformat_colorasfloat false`

**Comment by mgerhardy** [comment]
for voxedit the option is in the file dialog

![Bildschirmfoto vom 2023-07-31 13-15-38](https://github.com/mgerhardy/vengi/assets/577713/5ae7721e-14e5-473b-83b0-3ac8771af6f2)

**Comment by jerobarraco** [comment]
awesome thanks a lot!
it is quite definitely a error on float, i tried a goxel build that changes from byte to float and i've obtained the same issue.
i'll be testing your new build soon. thanks a lot!

**Comment by mgerhardy** [comment]
Closing this for now - as I can't test this myself. If it's still an issue, please fill a bug report at unreal.

**Comment by jerobarraco** [comment]
Thanks a lot.
i've reported to Epic long time ago.
thanks a lot for supporting with a compatibility feature.
i can confirm it does not crash anymore. but now it doesn't import with a different message (invalid primitive). i will open a new ticket for that since it sounds like a different issue.

**Comment by mgerhardy** [comment]
Can you give me the exact error message - than I can have a look at the unreal source code.

**Comment by mgerhardy** [comment]
https://github.com/EpicGames/UnrealEngine/blob/463443057fb97f1af0d2951705324ce8818d2a55/Engine/Plugins/Editor/GLTFImporter/Source/GLTFCore/Private/GLTF/GLTFReader.cpp#L3

**Comment by jerobarraco** [comment]
Yes, i've been busy. please give me some time and ill test again and record the info.

**Comment by jerobarraco** [comment]
https://github.com/EpicGames/UnrealEngine/blob/463443057fb97f1af0d2951705324ce8818d2a55/Engine/Plugins/Editor/GLTFImporter/Source/GLTFCore/Private/GLTF/GLTFReader.cpp#L241
that's the message i think.
i remember having that issue with vengi before depending how i export. but this time even changing the settings did not work.
