### ISSUE TITLE
VOXEDIT: Sort & group colors in palettes

### ISSUE THREAD

**Issue by JeffRockatansky** [mgerhardy/vengi#76]
Parameters could be:
* hue
* saturation
* brightness
* etc.

**Comment by mgerhardy** [comment]
Also see issue https://github.com/mgerhardy/engine/issues/74

**Comment by mgerhardy** [comment]
Manual sorting of colors will be in 0.0.20.

**Comment by mgerhardy** [comment]
You can now re-order the colors in the palette widget via drag and drop - if you hold the ctrl key the colors are replaced without changing the look of the model.

**Comment by mgerhardy** [comment]
![Bildschirmfoto vom 2023-02-10 17-43-31](https://user-images.githubusercontent.com/577713/218147574-308bc59d-cee7-425d-880f-48ddae7b701d.png)
![Bildschirmfoto vom 2023-02-10 17-43-28](https://user-images.githubusercontent.com/577713/218147578-c0f44c0f-9475-42b5-be69-72a20a4b16df.png)
![Bildschirmfoto vom 2023-02-10 17-43-25](https://user-images.githubusercontent.com/577713/218147581-5fa05a59-bf94-4ae1-9cfb-8408fd4980f4.png)

finally implemented - but i need to find a better place in the ui

**Comment by JeffRockatansky** [comment]
It might be better to place more darkened colors in starts of the rows and more lightened in the ends somehow. Depends on grid implementation that you've made.

**Comment by mgerhardy** [comment]
Do you mean to sort into the different direction? I can do asc and desc sorting easily if that’s what you mean

**Comment by JeffRockatansky** [comment]
No, I mean something like this

![Colors](http://archive.xaraxone.com/assets/images/kalms-colors.jpg)

**Comment by mgerhardy** [comment]
That’s going to be harder as you can change the dimensions of the palette panel and thus would reorder the palette each time

i begin to understand why magicavoxel introduced the imap chunk and made the ordering of the palette widget independent from the real color indices.

**Comment by mgerhardy** [comment]
I've now implemented palette indices, too - sorting is now possible without really changing the palette. The sorting algorithm that produces an order as you've shown in the screenshot is still a mystery for me though. Need to do some research on this.

**Comment by mgerhardy** [comment]
https://www.alanzucconi.com/2015/09/30/colour-sorting/
