### ISSUE TITLE
VOXELFORMAT: Add Qubicle QBCL support

### ISSUE THREAD

**Issue by mgerhardy** [mgerhardy/vengi#88]

**Comment by mgerhardy** [comment]
e49f54f8f3a166e6c5e106fb0c3c9cc3a709c0d7

**Comment by tostc** [comment]
Hey,

I've found this issue accidental and I've for a project of mine reverse engineered the .qbcl format. The spec is documented as gist [here](https://gist.github.com/tostc/7f049207a2e5a7ccb714499702b5e2fd)

**Comment by mgerhardy** [comment]
19bcb9dc1c293bbaf47086c6dfc107687d17a882 implemented the reading of qbcl - not sure about the scene positioning yet... and a few fields are still not known.

**Comment by mgerhardy** [comment]
@tostc you might be interested in it as I was able to identify one more field: the node data size.

**Comment by tostc** [comment]
@mgerhardy It's great that you identified a new field. But what is the unit of the size? In my test files the size is always 1 for all nodes. A small note for the following [line](https://github.com/mgerhardy/vengi/blob/19bcb9dc1c293bbaf47086c6dfc107687d17a882/src/modules/voxelformat/QBCLFormat.cpp#L193). I forgot to mention in my doc that the compressed data of the connection is a merged version of all the subnodes, which always seem to be matrices, but I'm not 100% sure.

**Comment by mgerhardy** [comment]
16435c98c7d1814941aacf873f3890b2b7adf643 added write support

**Comment by mgerhardy** [comment]
@tostc you are right - it's indeed not the size. I was wrong with it.

I also think that the the compound is a merged version - maybe to make loading easier for external software? No idea - the same is true for QBT afaik - see `QBTFormat::loadCompound` (`qbt::MergeCompounds`)

Thanks a lot for your reversing work - would have taken a lot longer without it.
